<a href="https://colab.research.google.com/github/eleonorabertoni/progetto_data_intensive/blob/main/progetto_data_intensive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
#%ls

hotel_bookings.csv  sample_data/

In [7]:
#import delle librerie
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

import os.path

In [14]:
booking_data_set = "hotel_bookings.csv"
with open(booking_data_set) as dataFile:
    data_raw = pd.read_csv(dataFile, sep=",")

data_raw.head()

          hotel  is_canceled  ...  reservation_status  reservation_status_date
0  Resort Hotel            0  ...           Check-Out               2015-07-01
1  Resort Hotel            0  ...           Check-Out               2015-07-01
2  Resort Hotel            0  ...           Check-Out               2015-07-02
3  Resort Hotel            0  ...           Check-Out               2015-07-02
4  Resort Hotel            0  ...           Check-Out               2015-07-03

[5 rows x 32 columns]